name: Deploy to Amazon S3 bucket

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credential@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy files to bucket
        run: aws s3 sync ./web s3://aws-cloud-resume
